schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "HogeInputType"
  types:
    HogeInputType:
      type: object
      description: "---"
      properties:
        vpc_cidr:
          type: string
          description: "VPC CIDR"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        subnet_cidr:
          type: string
          description: "SUBNET CIDR"
          default: 10.0.0.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
      required:
        - vpc_cidr
        - subnet_cidr